// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SailorMoon.Models
{
    public partial class ConduccionDescriptiva
    {
        public int IdConduccionDescriptiva { get; set; }
        public string Descripcion { get; set; }
        public string Periodo { get; set; }
        public int? IdEstudiante { get; set; }
        public string IdPersonal { get; set; }

        public virtual Estudiante IdEstudianteNavigation { get; set; }
    }
}