// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SailorMoon.Models
{
    public partial class Curso
    {
        public Curso()
        {
            Notas = new HashSet<Notas>();
            Personal = new HashSet<Personal>();
        }

        public int IdCurso { get; set; }
        public string NombreCurso { get; set; }

        public virtual ICollection<Notas> Notas { get; set; }
        public virtual ICollection<Personal> Personal { get; set; }
    }
}