// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SailorMoon.Models
{
    public partial class Estudiante
    {
        public Estudiante()
        {
            Asistencias = new HashSet<Asistencias>();
            ConduccionDescriptiva = new HashSet<ConduccionDescriptiva>();
            Notas = new HashSet<Notas>();
        }

        public int IdEstudiante { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public int? Dni { get; set; }
        public string Carnet { get; set; }
        [NotMapped]
        public IFormFile ImagenFile { get; set; }
        public string CodigoEst { get; set; }
        public int? IdGradoFk { get; set; }

        public virtual Grado IdGradoFkNavigation { get; set; }
        public virtual ICollection<Asistencias> Asistencias { get; set; }
        public virtual ICollection<ConduccionDescriptiva> ConduccionDescriptiva { get; set; }
        public virtual ICollection<Notas> Notas { get; set; }
    }
}