// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SailorMoon.Models
{
    public partial class Institucion
    {
        public int IdInstitucion { get; set; }
        public string Nombre { get; set; }
        public string Nivel { get; set; }
        public string CodigoModular { get; set; }
        public string Logo { get; set; }
    }
}