// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SailorMoon.Models
{
    public partial class NotasPeriodo
    {
        public int IdPeriodo { get; set; }
        public string NotaPeriodo1 { get; set; }
        public string NotaPeriodo2 { get; set; }
        public string NotaPeriodo3 { get; set; }
        public string NotaPeriodo4 { get; set; }
        public string PromedioAnual { get; set; }
        public int? IdNotas { get; set; }

        public virtual Notas IdNotasNavigation { get; set; }
    }
}