// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SailorMoon.Models
{
    public partial class Notas
    {
        public Notas()
        {
            NotasPeriodo = new HashSet<NotasPeriodo>();
        }

        public int IdNotas { get; set; }
        public double? Nota1 { get; set; }
        public double? Nota2 { get; set; }
        public double? Nota3 { get; set; }
        public double? Nota4 { get; set; }
        public double? Promedio { get; set; }
        public int? IdCurso { get; set; }
        public int? IdEstudianteFk { get; set; }

        public virtual Curso IdCursoNavigation { get; set; }
        public virtual Estudiante IdEstudianteFkNavigation { get; set; }
        public virtual ICollection<NotasPeriodo> NotasPeriodo { get; set; }
    }
}