// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SailorMoon.Models
{
    public partial class TipoUsuario
    {
        public TipoUsuario()
        {
            Personal = new HashSet<Personal>();
        }

        public int IdTipoUsuario { get; set; }
        public string Tipo { get; set; }

        public virtual ICollection<Personal> Personal { get; set; }
    }
}